Ana
TitoManri/CampusVirtualFidelitas pull request #3
Opened 2024-03-25 23:58 UTC by TitoManri

2024-03-25 23:59 UTC, TitoManri reviewed
prueba

2024-03-26 00:05 UTC, anapng requested changes
este pull era una prueba

2024-03-30 20:05 UTC, scara14 approved these changes
Revisado

2024-03-30 20:08 UTC, anapng commented
Revisado

2024-03-30 20:12 UTC, anapng approved these changes
Revisado

2024-03-30 20:29 UTC, merged